
server:
  port: 8082

spring:
  data:
    redis:
      host: localhost   # Redis ?????
      port: 6379        # Redis ???
      database: 0       # ?? Redis ?????? 0?
      timeout: 3s       # ??????
      connect-timeout: 3s  # ?????Spring Boot 3.x ???
      client-type: lettuce # ?? Redis ????????? lettuce?
      lettuce:
        pool:
          enabled: true    # ?????
          max-active: 8    # ??????-1 ??????
          max-idle: 8      # ???????
          min-idle: 0      # ???????
          max-wait: -1ms   # ??????????-1 ?????
  application:
    name: @artifactId@
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        username: nacos
        password: nacos
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/joker-svr?serverTimezone=GMT%2B8&characterEncoding=utf8&&allowMultiQueries=true&useSSL=false
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource
  #    druid:
  #      min-idle: 1                                          # ?????
  #      max-active: 100                                         # ?????(??8)
  #      max-wait: 1000                                       # ????????????
  #      min-evictable-idle-time-millis: 300000               # ????????????????????
  #      time-between-eviction-runs-millis: 60000             # ????????????????????????

mybatis:
  mapper-locations: classpath:mapper/*.xml
  #??????
  configuration:
    map-underscore-to-camel-case: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
scheduler:
  bucketsNum: 5
  tryLockSeconds: 70
  tryLockGapMilliSeconds: 100
  successExpireSeconds: 130
  pool:
    corePoolSize: 100
    maxPoolSize: 100
    queueCapacity: 99999
    namePrefix: scheduler-


trigger:
  zrangeGapSeconds: 1
  workersNum: 10000
  pool:
    corePoolSize: 100
    maxPoolSize: 100
    queueCapacity: 99999
    namePrefix: trigger-

migrator:
  workersNum: 1000
  migrateStepMinutes: 60
  migrateTryLockMinutes: 1
  migrateSuccessExpireMinutes: 1
  timerDetailCacheMinutes: 2
